server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.1.41.152:3306/test127?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: guojiahong
    password: 88hello521H

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true #开启驼峰字段自动转下划线
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl